### ISSUE TITLE
Does not work with Angular 6

### ISSUE THREAD

**Issue by ankitbtanna** [jurebajt/coffee-election#1]
Hi Jure Bajt  - I have tried the same approach with Angular 6 but it failed. My Github link is 
[Github - RxJS store](https://github.com/1wQasdTeedFrsweXcs234saS56Scxs5423/flight-search-portal-web)

You can find my store in src/app/domain-model  and Search Flight component folder. In ngOnInit I am fetching the airport list and using model-mapper to build my required JSON. Have I missed anything? the this.state seems to give me the correct number but not the state$ observable.

**Comment by georgebyte** [comment]
Closing as the solution to your problem was described in a comment on my blog: http://disq.us/p/1v9wlja.
